# Generated by Django 5.2.8 on 2025-12-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dht11',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='dht11',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='dht11',
            name='sensor_id',
        ),
        migrations.RemoveField(
            model_name='dht11',
            name='temperature',
        ),
        migrations.AddField(
            model_name='dht11',
            name='dt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dht11',
            name='hum',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dht11',
            name='temp',
            field=models.FloatField(null=True),
        ),
    ]
